name: Email_on_Push

on:
  push:
    branches:
      - dev

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send email notification
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          RECIPIENT_EMAIL: "destinyhub237@gmail.com"
          SENDER_EMAIL: "destinyhub237@gmail.com"
        run: |
          echo "Envoi de la notification par email..."
          curl --request POST \
            --url https://api.sendgrid.com/v3/mail/send \
            --header "Authorization: Bearer $SENDGRID_API_KEY" \
            --header "Content-Type: application/json" \
            --data '{
              "personalizations": [{
                "to": [{"email": "'$RECIPIENT_EMAIL'"}],
                "subject": "Nouveau Push GitHub de '$COMMIT_AUTHOR'",
                "dynamic_template_data": {
                  "commit_message": "'$COMMIT_MESSAGE'"
                }
              }],
              "from": {"email": "'$SENDER_EMAIL'"},
              "content": [{
                "type": "text/plain",
                "value": "Un nouveau push a été effectué avec le message : '$COMMIT_MESSAGE'"
              }]
            }'

      - name: Vérification de l’envoi
        if: ${{ failure() }}
        run: echo "Échec de l’envoi de l’email"